name: Build Armadillo

on:
  pull_request:
    branches: [ main ]
    paths:
      - "recipes/armadillo/**"
      - "profiles/**"
      - ".github/workflows/build-armadillo.yml"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC 14 and aarch64 cross-compiler
        run: |
          sudo apt update
          sudo apt install -y gcc-14 g++-14

          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100

      - name: Install Conan
        run: pip install conan

      - name: Conan config
        run: conan profile detect --force

      - name: Authenticate Conan
        run: |
          conan remote add conancenter https://center2.conan.io --force
          conan remote add conanmrgi https://conan-upload.mrgi23.com/artifactory/api/conan/Conan-Index --force
          conan remote login conanmrgi ${{ vars.CONAN_USER }} -p ${{ secrets.CONAN_PASS }}

      - name: Build Armadillo
        run: |
          conan create recipes/armadillo \
          --name=armadillo \
          --version=14.0.2 \
          --user=mrgi \
          --channel=release \
          -pr:b=profiles/build-linux-x86_64 \
          --build=missing

      - name: Remove old package
        run: |
          conan remove "armadillo/14.0.2@mrgi/release" -r=conanmrgi -c

      - name: Upload package
        run: |
          conan upload "armadillo/14.0.2@mrgi/release" -r=conanmrgi --force
