name: Build Aubio

on:
  workflow_call:
    inputs:
      CONAN_USER:
        required: true
        type: string
    secrets:
      CONAN_PASS:
        required: true

jobs:
  build-aubio:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Conan
        run: pip install conan

      - name: Conan config
        run: conan profile detect --force

      - name: Authenticate Conan
        run: |
          conan remote add conancenter https://center2.conan.io --force
          conan remote add conanmrgi https://conan-upload.mrgi23.com/artifactory/api/conan/Conan-Index --force
          conan remote login conanmrgi ${{ inputs.CONAN_USER }} -p ${{ secrets.CONAN_PASS }}

      - name: Build Aubio
        run: |
          conan create recipes/aubio \
          --name=aubio \
          --version=0.4.9 \
          --user=mrgi \
          --channel=release \
          -pr:b=profiles/build-linux-x86_64 \
          --build=missing

      - name: Remove old package
        run: |
          conan remove "aubio/0.4.9@mrgi/release" -r=conanmrgi -c

      - name: Upload package
        run: |
          conan upload "aubio/0.4.9@mrgi/release" -r=conanmrgi --force
